const item = [
  "Silent Shadows",
  "Lonely Light",
  "Quiet Void",
  "Fading Contrast",
  "Empty Horizon",
  "Monochrome Silence",
  "Dark Whisper",
  "Pale Echo",
  "Stark Solitude",
  "Bleak Reflection",
  "Isolated Shade",
  "Muted Dusk",
  "Grey Emptiness",
  "Cold Absence",
  "Bare Twilight",
  "Still Dusk",
  "Vacant Gloom",
  "Quiet Eclipse",
  "Dim Silence",
  "Hollow Night"
];
